import {Injectable} from '@angular/core';
import { TblRegproDocumentoModel } from "../../models/tblregprosolicitud/tblRegprodocumento.model";

@Injectable()
export class TblregprosolicitudModel {
    public codigo: string;
    public idDistrito: string;
    public cCodsoli: string;
    public nIdTipsoli: number;
    public cCodmod: string;
    public nIdTipprog: number;
    public cNomprog: string;
    public nProlat?: number;
    public nProlon?: number;
    public nIdTipgest: number;
    public nIdTipdepe: number;
    public nIdTipeges: number;
    public nIdTipturn: number;
    public nIdTipcjes: number;
    public nIdTipvia?: number;
    public cDirnomvia: string;
    public cDirnumvia: string;
    public cDirmz: string;
    public cDirlote: string;
    public nIdTiplocd: number;
    public cDirlocd: string;
    public cDiretap: string;
    public cDirsect: string;
    public cDirzona: string;
    public cDirotro: string;
    public cDirrefe: string;
    public cCodccpp: string;
    public cNomccpp: string;
    public nCcpplat?: number;
    public nCcpplon?: number;
    public cCsemc: string;
    public cNomsemc: string;
    public nSemclat?: number;
    public nSemclon?: number;
    public nIdTipprag?: number;
    public cOtrpragua: string;
    public cSumagua: string;
    public nIdTippren?: number;
    public cOtrprener: string;
    public cSumener: string;
    public nIdTipsitu: number;
    public cUsuenv: string;
    public cNomusuenv : string;
    public dFecenv?: Date;
    public cUsumodi: string;
    public cNomusumodi: string;
    public dFecmodi?: Date;
    public cUsurevi: string;
    public cNomusurevi: string;
    public dFecrevi?: Date;
    public cUsurevs: string;
    public cNomusurevs: string;
    public dFecrevs?: Date;
    public dFecaten?: Date;
    public cUsucre: string;
    public dFecumo?: Date;
    public cUsuumo: string;
    public cGeohash: string;
    public cCodArea: string;
    public cCodAreasig: string;
    public nIdTipsituprog?: number;
    public nIdTipsiturev?: number;
    public nIdTipsiturevsig?: number;
    public cIndult: string;
    public nIdTipoperiodo: number;
    public cEstado: string;
    public documento: TblRegproDocumentoModel;
    public croquis: File;
    public file1: File;
    public file2: File;
    public file3: File;
    public file4: File;
    public file5: File;   
}

